

from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
from datetime import datetime
import hermes
import json

# storage hierarchy

import sqlite3

def setup_database():
    # Connect to (or create) the SQLite database
    conn = sqlite3.connect('cyber_prompts.db')
    cursor = conn.cursor()

    # 1. Create the hierarchy table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS categories (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL UNIQUE,
            parent_id INTEGER,
            FOREIGN KEY (parent_id) REFERENCES categories (id)
        )
    ''')
    
    # 2. Create the table for saving the allowed prompts
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS valid_prompts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            prompt_text TEXT NOT NULL,
            category_id INTEGER,
            FOREIGN KEY (category_id) REFERENCES categories (id)
        )
    ''')
    
    conn.commit()
    return conn, cursor

conn, cursor = setup_database()

app = Flask(__name__, static_folder=".", static_url_path="")
CORS(app) 
# app states
state = {
    "token": None,
    "duckdb_conn": None,
}


def _bootstrap():
    """Run once when the API starts: authenticate, pull alerts, load DuckDB."""
    print("Starting Hermes API...")

    token = hermes.get_wazuh_token(
        hermes.MANAGER_URL, hermes.WAZUH_USERNAME, hermes.WAZUH_PASSWORD
    )
    state["token"] = token

    alerts = hermes.get_alerts(
        hermes.INDEXER_URL, hermes.INDEXER_USERNAME, hermes.INDEXER_PASSWORD
    )
    processed = hermes.process_alerts(alerts)
    state["duckdb_conn"] = hermes.load_into_duckdb(processed)

    print("Hermes API ready.")


# Routes 

@app.route("/", methods=["GET"])
def index():
    """Serve the React frontend."""
    """Serve the plain HTML/JS interface — no Node/npm required."""
    return send_from_directory(".", "index.html")


@app.route("/api/health", methods=["GET"])
def health():
    wazuh_ok = state["token"] is not None
    duckdb_ok = state["duckdb_conn"] is not None
    row_count = 0
    if duckdb_ok:
        try:
            row_count = state["duckdb_conn"].execute("SELECT COUNT(*) FROM threats").fetchone()[0]
        except Exception:
            row_count = 0
    return jsonify({
        "wazuh_authenticated": wazuh_ok,
        "duckdb_ready": duckdb_ok,
        "threats_row_count": row_count,
        "model": hermes.OLLAMA_MODEL,
    })


@app.route("/api/agents", methods=["GET"])
def agents():
    """Return a list of Wazuh agents."""
    if not state["token"]:
        return jsonify({"error": "Not authenticated with Wazuh"}), 503
    data = hermes.get_agents(hermes.MANAGER_URL, state["token"])
    return jsonify(data)


@app.route("/api/refresh", methods=["POST"])
def refresh():
    """Refresh the DuckDB database with the latest alerts from Wazuh."""
    if not state["duckdb_conn"]:
        return jsonify({"error": "DuckDB not initialized"}), 503
    count = hermes.refresh_threats(
        state["duckdb_conn"], hermes.INDEXER_URL,
        hermes.INDEXER_USERNAME, hermes.INDEXER_PASSWORD
    )
    return jsonify({"status": "refreshed", "rows": count})


@app.route("/api/latest-alert", methods=["GET"])
def latest_alert():
    """Return the single most recent raw alert (full nested JSON) for
    the Alert Analyzer component's 'Fetch Live Alert' button.
    method: GET /api/latest-alert
    """
    alert = hermes.get_latest_alert(
        hermes.INDEXER_URL, hermes.INDEXER_USERNAME, hermes.INDEXER_PASSWORD
    )
    if alert is None:
        return jsonify({"error": "No alerts found"}), 404
    return jsonify(alert)


@app.route("/api/query", methods=["POST"])
def query():
    """Accept a natural language question, generate SQL, and return results."""
    body = request.get_json(silent=True) or {}
    question = body.get("question", "").strip()

    if not question:
        return jsonify({"error": "Missing 'question' in request body"}), 400
    if not state["duckdb_conn"]:
        return jsonify({"error": "DuckDB not initialized"}), 503

    sql, result_df, summary = hermes.query_engine(question, state["duckdb_conn"])
    viz = hermes.describe_result(result_df)

    return jsonify({
        "question": question,
        "sql": sql,
        "summary": summary,
        "visualization": viz,
    })


def log_query_to_file(question, sql, result_df, path="query_log.txt"):
    """Append every user query and its generated SQL to a plain text log.
    question: the user's natural language question
    sql: the SQL generated by the query engine"""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(path, "a", encoding="utf-8") as f:
        f.write(f"[{timestamp}]\n")
        f.write(f"Question: {question}\n")
        f.write(f"SQL: {sql}\n")
        f.write("-" * 60 + "\n")
        f.write(f"Rows returned: {len(result_df) if result_df is not None else 0}\n")

if __name__ == "__main__":
    _bootstrap()
    app.run(host="127.0.0.1", port=5000, debug=False)