import requests
import urllib3
import ollama
import duckdb
import pandas as pd
import re
import requests
import urllib3
import matplotlib.pyplot as plt
# disable warnings for self-signed certificates
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)



#my wazuh manager is running on this IP and port
MANAGER_URL = "https://10.0.0.39:55000"  # agent management
INDEXER_URL = "https://localhost:9200"   # actual alert data

# Function to authenticate and get a token
def get_wazuh_token(base_url, username, password):
    '''Authenticate with the Wazuh API and return the token
    base_url: The base URL of the Wazuh API (e.g., https://your-wazuh-manager:55000)
    username: The Wazuh API username
    password: The Wazuh API password'''
    response = requests.post(
        f"{base_url}/security/user/authenticate",
        auth=(username, password),
        verify=False
    )
    if response.status_code == 200:
        token = response.json()['data']['token']
        print("Authenticated successfully!")
        return token
    else:
        print(f"Authentication failed: {response.json()}")
        return None

def get_agents(base_url, token):
    '''Get the list of monitored machines (agents) from the Wazuh API
    base_url: The base URL of the Wazuh API
    token: The authentication token'''
    headers = {"Authorization": f"Bearer {token}"}
    response = requests.get(
        f"{base_url}/agents",
        headers=headers,
        verify=False
    )
    print("Status code:", response.status_code)
    print("Response:", response.json())
    return response.json()

# Authenticate
token = get_wazuh_token(MANAGER_URL, "wazuh", "wazuh")

# Get monitored machines
agents = get_agents(MANAGER_URL, token)



def get_alerts(base_url_indexer, username, password, limit=50):
    response = requests.get(
        f"{base_url_indexer}/wazuh-alerts*/_search",
        auth=(username, password),
        params={"size": limit},
        verify=False
    )
    print("Status code:", response.status_code)
    print("Response:", response.json())
    return response.json()


# Example response structure from Elasticsearch (this is just a placeholder, the actual response will depend on your data)
response = {
    "hits": {
        "hits": [
            {
                "_source": {
                    "timestamp": "2026-06-01T...",
                    "agent": {"name": "wazuh-server"},
                    "rule": {"level": 5, "description": "..."},
                    "data": {...}
                }
            },
            # more alerts...
        ]
    }
}

# Function to process the raw alerts response and extract relevant information
def process_alerts(alerts_response):
    '''Process the raw alerts response from Elasticsearch and extract relevant information
    alerts_response: The raw JSON response from the Elasticsearch query'''
    processed_alerts = []
    for hit in alerts_response['hits']['hits']:
        alert = hit['_source']
        processed_alerts.append({
            "timestamp": alert.get('timestamp'),
            "agent_name": alert.get('agent', {}).get('name'),
            "rule_level": alert.get('rule', {}).get('level'),
            "rule_description": alert.get('rule', {}).get('description'),
            "data": alert.get('data')
        })
    print("u ladies aight?")
    return processed_alerts


# Function to load processed alerts into DuckDB
def load_into_duckdb(processed_alerts):
    '''Load the processed alerts into DuckDB for analysis
    processed_alerts: A list of dictionaries containing the processed alert information'''
    
    df = pd.DataFrame(processed_alerts)
    conn = duckdb.connect(database=':memory:')
    conn.execute("CREATE TABLE threats AS SELECT * FROM df")
    print("threats loaded into DuckDB successfully!")
    return conn


# Function to get the schema of the threats table
def get_schema(conn):
    connect = conn.execute(f"DESCRIBE threats").fetchdf()
    return connect.to_string()


# Function to translate natural language queries into SQL using Ollama
def sql_translate(user_query, schema):
    '''Translate a natural language query into SQL based on the provided schema
    user_query: The natural language query from the user
    schema: The schema of the threats table in DuckDB'''
    messages = ollama.chat(model = "qwen2.5", messages = [
        {"role": "system", "content": f"You are a helpful assistant that translates natural language queries into SQL. The schema of the threats table is: {schema}"},
        {"role": "user", "content": user_query}
    ])
    response = messages['message']['content']
    return response

# Function to clean SQL query
def sql_cleaner(sql_query):
    '''Clean the generated SQL query to ensure it is safe and valid
    sql_query: The output generated by Qwen2.5'''
    # Basic cleaning steps (this can be expanded with more robust checks)
    match = re.search(r'```sql\s*(.*?)\s*```', sql_query, re.DOTALL)
    if match:
        pristine_query = match.group(1).strip()
        return pristine_query
    return sql_query.strip()


# Function to execute the cleaned SQL query against the DuckDB database
def run_query(conn, sql_query):
    '''Execute the cleaned SQL query against the DuckDB database
    conn: The DuckDB connection object
    sql_query: The cleaned SQL query to execute'''
    runner =conn.execute(sql_query)
    result = runner.fetchdf()
    return result

def visualizer(df):
    '''Visualize the query results using a simple bar chart
    df: The DataFrame containing the query results'''
    if df.empty:
        print("No data to visualize.")
        return
    rows, cols = df.shape
    if rows == 1 and cols == 1:
        print("Single value result:", df.iloc[0, 0])
    elif cols == 2 and pd.api.types.is_numeric_dtype(df.iloc[:, 1]):
        plt.bar(df.iloc[:, 0], df.iloc[:, 1])
        plt.xlabel(df.columns[0])
        plt.ylabel(df.columns[1])
        plt.title("Query Results Visualization")
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()
    elif 'timestamp' in df.columns:
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        df.set_index('timestamp', inplace=True)
        df.plot(kind='line')
        plt.xlabel("Time")
        plt.ylabel("Values")
        plt.title("Time Series Visualization")
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()
    else:
        print("Query Result:\n", df)
# Putting it all together example usage

# Get alerts from Elasticsearch (Wazuh Indexer)
alerts = get_alerts(INDEXER_URL, "admin", "Hermes25?")
processed_alerts = process_alerts(alerts)
#Load into DuckDB
duckdb_conn = load_into_duckdb(processed_alerts)
#create a sample table and query it
result = duckdb_conn.execute("SELECT * FROM threats LIMIT 3").fetchdf()
print(result)
#Get the schema of the threats table
schema = get_schema(duckdb_conn)
print("Schema of threats table:\n", schema)
#Test natural language query
user_query = "Show me the top 5 most recent alerts with a rule level of 2 or higher."
#Translate the natural language query into SQL
sql_query = sql_translate(user_query, schema)
#return the cleaned SQL query
cleaned_sql_query = sql_cleaner(sql_query)
query_result = run_query(duckdb_conn, cleaned_sql_query)
print("Query Result:" , query_result)
#visualize data
visualizer(query_result)